In [1]:
#Load in Numpy 
import numpy as np

# The Basics

In [2]:
#The Basics
a = np.array ([1,2,3], dtype = 'int16') #you can change dtype 
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim
b.ndim

2

In [5]:
# Get Shape
a.shape

(3,)

In [6]:
# Get Type
a.dtype

dtype('int16')

In [7]:
# Get Size
a.itemsize

2

In [8]:
# Get total size
a.size * a.itemsize

6

In [9]:
# Get total size
a.nbytes

6

# Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# Get a specific element [r, c]
# [row 1, the second last element]
a[1, -2]

13

In [18]:
# Get a speicific row
#[row 0, all elements]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get a specifc column
#[all rows, second element]
a[:, 2]

array([ 3, 10])

In [20]:
# Getting a little more fancy [row, startindex:endindex:stepsize] 
# endindex is exclusive, i.e. entering 6 gives you the 5th element in the row
# [row 0, starting at element 1 to element 6, two steps at a time]
a[0, 1:6:2]

array([2, 4, 6])

In [21]:
# Getting a  little more fancy [row, startindex:endindex:stepsize]
# [row 0, element 1 to the last index, two steps at a time] 
a[0, 1:-1:2]

array([2, 4, 6])

In [25]:
a[1,5] = 20
#inserts a 20 into row 1 at index 5
# print(a)

a[:,2] = 5
#inserts a 5 into all rows at index 2
#print(a)

a[:,2] = [1,2]
#at index 2, inserts a 1 into row 0, and a 2 into row 1
#inserts a 1 into index 2 of row 0, 
#and inserts a 2 index 2 of row 1 

print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


## 3-d example

In [28]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Get specific element (work outside in) [set, row, index]
b[0,1,1] # [the 0th set, 1st row index, 1st element]
b[:,1,:] # [all sets, 1st row index, all elements] 
b[0,1,1] # [0th set, 1st row index, 1st element]  

4

In [37]:
# replace
b[:,1,:] = [[9,9], [8,8]] 
#replaces the 0th set, 0th row with [9,9], 
#replaces the 1st set, 1st row with [8,8]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [38]:
# A matrix of 0s
np.zeros((2,3,3)) #3D array of 0s

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#A matrix of 1s
np.ones((4,2,2) , dtype = 'int32') #3D array of 1s, dtype set to int32

In [40]:
#A matrix of any other number
np.full ((2,2), 99, dtype = 'float32') #2 by 2 array of 99s, dtype set to float32

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [42]:
# Any other number (full_like)
#Return a full array with the same shape and type as a given array.
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# Random decimal numbers
# Create an array of the given shape and populate it with random samples from a uniform distribution between 0 and 1
np.random.rand(4,2)

array([[0.53232528, 0.17195871],
       [0.95779448, 0.20256853],
       [0.69427295, 0.13137487],
       [0.40815039, 0.01304585]])

In [45]:
#Random Integer values
#Return random integers from low (inclusive) to high (exclusive).
np.random.randint(7, size=(3,3))

array([[5, 5, 6],
       [3, 4, 4],
       [3, 1, 6]])

In [47]:
np.identity(3)
#Return the identity array.
#The identity array is a square array with ones on the main diagonal.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
#np.repeat: Repeat elements of an array
# help(np.repeat)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9

print(z)

output[1:4, 1:4] = z #remember when slicing the number on the right side of the colon is exclusive
#replaces rows 1 to 3, columns 1 to 3 with z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
